name = "thE garDEN"
author = "Eden Fujikaze"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c2eb4855934554a5dbcd3a6df6ccdcd265c5f07b70c78797d8a0c047e4b423d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
