name = "thE garDEN"
author = "Eden Fujikaze"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f1d5c923d3ba86386610f3ba9ea8552d55f18d9ea07782585ff604374bd8f61"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
