name = "thE garDEN"
author = "Eden Fujikaze"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cdf96e9b39b275f7da2475e8f0674a09d980248dfff15c76ae907e21d3d3865"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
