name = "gardenServer"
author = "Eden Fujikaze"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecb4fef8d566946b987f98037f674e9110a99a8e3d6cd202212b8f9db7c07452"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
