name = "gardenServer"
author = "Eden Fujikaze"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a99073e3a351380f07c438748a0d623012a3575619dad1c565f924e5c9343b0d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
