name = "gardenServer"
author = "Eden Fujikaze"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5b9d62c5b8472aa9dda9cfe075c777c7952dcb64e8f350cae3812a6158105c9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
